// Incidents rendered by the app.
//
// Not hand-written: incidents.json is generated by scripts/export_incidents.py,
// which runs the real detectors over real attack telemetry. Regenerate it after
// changing detection or correlation.
//
// Sections the agent would populate — entity memory, prior-sighting recall,
// confirmed and refuted hypotheses — are empty here, because the agent does not
// exist yet. They are left empty rather than filled with plausible fiction.

import payload from "./incidents.json";

export type Severity = "critical" | "high" | "medium" | "low" | "info";
export type IncidentStatus =
  | "triage"
  | "investigating"
  | "contained"
  | "closed"
  | "false_positive";
export type HypothesisStatus = "open" | "confirmed" | "refuted";
export type Verdict = "malicious" | "suspicious" | "benign" | "unknown";
export type EntityKind = "ip" | "domain" | "hash" | "user" | "host" | "process";

export interface Hypothesis {
  id: string;
  statement: string;
  status: HypothesisStatus;
  confidence: number;
  supporting: number;
  contradicting: number;
  note?: string | null;
}

export interface TimelineEvent {
  seq: number;
  at: string;
  action: string;
  actor: string;
  technique?: string;
  occurrences: number;
}

export interface EntityMemory {
  kind: EntityKind;
  value: string;
  verdict: Verdict;
  reasoning: string;
  timesSeen: number;
  firstSeen: string;
  riskScore: number;
  clearedCount: number;
}

export interface Incident {
  ref: string;
  title: string;
  severity: Severity;
  status: IncidentStatus;
  host: string;
  user: string;
  technique?: string;
  tactics: string[];
  openedAt: string;
  alertCount: number;
  summary?: string;
  resembles?: { ref: string; similarity: number; why: string };
  hypotheses: Hypothesis[];
  timeline: TimelineEvent[];
  entities: EntityMemory[];
}

export interface Provenance {
  events: number;
  alerts: number;
  incidents: number;
  source: string;
}

export const provenance = payload.generated as Provenance;
export const incidents = payload.incidents as unknown as Incident[];

export function getIncident(ref: string): Incident | undefined {
  return incidents.find((i) => i.ref.toLowerCase() === ref.toLowerCase());
}

export const queueStats = {
  open: incidents.filter((i) => i.status === "triage" || i.status === "investigating")
    .length,
  autoCleared: incidents.filter((i) => i.status === "false_positive").length,
  alerts: provenance.alerts,
};

// Entity memory is the agent's long-term store. Empty until it has run.
export const knownEntities: EntityMemory[] = [];
